version: '3'

services:
  consul:
    image: consul:1.4.2
    ports:
      - "8500:8500"
    hostname: consul
    container_name: consul
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
        RABBITMQ_ERLANG_COOKIE: admin
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
    ports:
        - 5672:5672
        - 15672:15672
    hostname: rabbitmq